# .pre-commit-config.yaml
repos:
- repo: local
  hooks:
    - id: validate-openapi
      name: Validate OpenAPI Spec
      entry: python scripts/validate_openapi.py
      language: system
      types: [python] # Garante que sรณ roda se arquivos Python forem alterados
      pass_filenames: false